-- ============================================
-- V42: Leader Research Agent
-- ============================================

CREATE TABLE IF NOT EXISTS leader_research_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Research run ID',
    status VARCHAR(30) NOT NULL COMMENT 'RUNNING/SUCCESS/PARTIAL_FAILURE/FAILED/SKIPPED',
    trigger_type VARCHAR(30) NOT NULL DEFAULT 'MANUAL' COMMENT 'MANUAL/SCHEDULED/PREVIEW',
    dry_run TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否预览运行',
    started_at BIGINT NOT NULL COMMENT '开始时间',
    finished_at BIGINT DEFAULT NULL COMMENT '结束时间',
    duration_ms BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    source_counts_json TEXT DEFAULT NULL COMMENT '来源统计 JSON',
    candidate_counts_json TEXT DEFAULT NULL COMMENT '候选统计 JSON',
    error_class VARCHAR(255) DEFAULT NULL COMMENT '错误类型',
    error_message TEXT DEFAULT NULL COMMENT '错误信息',
    partial_failure TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否部分失败',
    skipped_reason VARCHAR(255) DEFAULT NULL COMMENT '跳过原因',
    last_event_cursor VARCHAR(255) DEFAULT NULL COMMENT '事件处理游标',
    created_at BIGINT NOT NULL COMMENT '创建时间',
    updated_at BIGINT NOT NULL COMMENT '更新时间',
    INDEX idx_leader_research_run_status_started (status, started_at),
    INDEX idx_leader_research_run_started (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Leader research run records';

CREATE TABLE IF NOT EXISTS leader_research_candidate (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Research candidate ID',
    normalized_wallet VARCHAR(42) NOT NULL COMMENT '小写钱包地址',
    leader_id BIGINT DEFAULT NULL COMMENT '关联 Leader ID',
    pool_id BIGINT DEFAULT NULL COMMENT '关联 Leader Pool ID',
    research_state VARCHAR(30) NOT NULL DEFAULT 'DISCOVERED' COMMENT '研究状态',
    source VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN' COMMENT '主来源',
    source_rank INT DEFAULT NULL COMMENT '来源排名',
    score DECIMAL(20, 8) DEFAULT NULL COMMENT '当前总分',
    score_version VARCHAR(100) DEFAULT NULL COMMENT '评分版本',
    reason TEXT DEFAULT NULL COMMENT '推荐原因',
    risk_flags TEXT DEFAULT NULL COMMENT '风险标记，逗号或 JSON',
    locked TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否锁定',
    agent_owned TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否由 agent 创建/管理',
    provenance VARCHAR(50) NOT NULL DEFAULT 'AGENT_CREATED' COMMENT '来源归属',
    source_evidence TEXT DEFAULT NULL COMMENT '来源证据摘要 JSON',
    first_seen_at BIGINT NOT NULL COMMENT '首次发现时间',
    last_source_seen_at BIGINT DEFAULT NULL COMMENT '最后来源新鲜时间',
    last_scored_at BIGINT DEFAULT NULL COMMENT '最后评分时间',
    cooldown_until BIGINT DEFAULT NULL COMMENT '冷却截止时间',
    cooldown_count INT NOT NULL DEFAULT 0 COMMENT '冷却次数',
    last_transition_at BIGINT DEFAULT NULL COMMENT '最后状态迁移时间',
    trial_ready_at BIGINT DEFAULT NULL COMMENT '进入试跟建议时间',
    retired_at BIGINT DEFAULT NULL COMMENT '退休时间',
    last_paper_session_id BIGINT DEFAULT NULL COMMENT '最后纸跟 session',
    created_at BIGINT NOT NULL COMMENT '创建时间',
    updated_at BIGINT NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_leader_research_candidate_wallet (normalized_wallet),
    INDEX idx_leader_research_candidate_state_seen (research_state, last_source_seen_at),
    INDEX idx_leader_research_candidate_leader (leader_id),
    INDEX idx_leader_research_candidate_pool (pool_id),
    INDEX idx_leader_research_candidate_score (score),
    CONSTRAINT fk_leader_research_candidate_leader FOREIGN KEY (leader_id) REFERENCES copy_trading_leaders(id) ON DELETE SET NULL,
    CONSTRAINT fk_leader_research_candidate_pool FOREIGN KEY (pool_id) REFERENCES copy_trading_leader_pool(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Leader research candidates';

CREATE TABLE IF NOT EXISTS leader_research_score (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Research score ID',
    candidate_id BIGINT NOT NULL COMMENT '候选 ID',
    run_id BIGINT DEFAULT NULL COMMENT '运行 ID',
    score_version VARCHAR(100) NOT NULL COMMENT '评分版本',
    total_score DECIMAL(20, 8) NOT NULL DEFAULT 0 COMMENT '总分',
    profit_signal DECIMAL(20, 8) NOT NULL DEFAULT 0,
    repeatability DECIMAL(20, 8) NOT NULL DEFAULT 0,
    liquidity_fit DECIMAL(20, 8) NOT NULL DEFAULT 0,
    entry_price_fit DECIMAL(20, 8) NOT NULL DEFAULT 0,
    slippage_risk DECIMAL(20, 8) NOT NULL DEFAULT 0,
    holding_period_fit DECIMAL(20, 8) NOT NULL DEFAULT 0,
    market_type_risk DECIMAL(20, 8) NOT NULL DEFAULT 0,
    drawdown_risk DECIMAL(20, 8) NOT NULL DEFAULT 0,
    exit_liquidity_risk DECIMAL(20, 8) NOT NULL DEFAULT 0,
    data_freshness DECIMAL(20, 8) NOT NULL DEFAULT 0,
    filter_pass_rate DECIMAL(20, 8) NOT NULL DEFAULT 0,
    sample_trade_count INT NOT NULL DEFAULT 0 COMMENT '样本交易数',
    reason TEXT DEFAULT NULL COMMENT '评分解释',
    created_at BIGINT NOT NULL COMMENT '创建时间',
    INDEX idx_leader_research_score_candidate_created (candidate_id, created_at),
    INDEX idx_leader_research_score_run (run_id),
    CONSTRAINT fk_leader_research_score_candidate FOREIGN KEY (candidate_id) REFERENCES leader_research_candidate(id) ON DELETE CASCADE,
    CONSTRAINT fk_leader_research_score_run FOREIGN KEY (run_id) REFERENCES leader_research_run(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Leader research score history';

CREATE TABLE IF NOT EXISTS leader_research_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Research event ID',
    candidate_id BIGINT DEFAULT NULL COMMENT '候选 ID',
    run_id BIGINT DEFAULT NULL COMMENT '运行 ID',
    event_type VARCHAR(50) NOT NULL COMMENT '事件类型',
    reason TEXT DEFAULT NULL COMMENT '原因',
    payload_summary TEXT DEFAULT NULL COMMENT 'payload 摘要',
    notification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT '通知状态',
    notification_error TEXT DEFAULT NULL COMMENT '通知错误',
    dedupe_key VARCHAR(255) DEFAULT NULL COMMENT '事件去重 key',
    created_at BIGINT NOT NULL COMMENT '创建时间',
    notified_at BIGINT DEFAULT NULL COMMENT '通知时间',
    UNIQUE KEY uk_leader_research_event_dedupe (dedupe_key),
    INDEX idx_leader_research_event_candidate_created (candidate_id, created_at),
    INDEX idx_leader_research_event_run (run_id),
    INDEX idx_leader_research_event_type_created (event_type, created_at),
    INDEX idx_leader_research_event_notification (notification_status, created_at),
    CONSTRAINT fk_leader_research_event_candidate FOREIGN KEY (candidate_id) REFERENCES leader_research_candidate(id) ON DELETE SET NULL,
    CONSTRAINT fk_leader_research_event_run FOREIGN KEY (run_id) REFERENCES leader_research_run(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Leader research events';

CREATE TABLE IF NOT EXISTS leader_research_source_state (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Source state ID',
    source_type VARCHAR(50) NOT NULL COMMENT '来源类型',
    status VARCHAR(30) NOT NULL DEFAULT 'DISABLED' COMMENT 'SUCCESS/FAILURE/STALE/DISABLED/DEGRADED',
    last_success_at BIGINT DEFAULT NULL,
    last_failure_at BIGINT DEFAULT NULL,
    last_run_at BIGINT DEFAULT NULL,
    last_candidate_count INT NOT NULL DEFAULT 0,
    error_class VARCHAR(255) DEFAULT NULL,
    error_message TEXT DEFAULT NULL,
    stale TINYINT(1) NOT NULL DEFAULT 0,
    disabled_reason VARCHAR(255) DEFAULT NULL,
    last_cursor VARCHAR(255) DEFAULT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY uk_leader_research_source_state_type (source_type),
    INDEX idx_leader_research_source_state_status (status),
    INDEX idx_leader_research_source_state_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Leader research source health';

CREATE TABLE IF NOT EXISTS leader_activity_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Activity event ID',
    source VARCHAR(50) NOT NULL COMMENT '来源',
    source_event_id VARCHAR(255) DEFAULT NULL COMMENT '来源事件 ID',
    stable_event_key VARCHAR(255) NOT NULL COMMENT '稳定去重 key',
    normalized_wallet VARCHAR(42) DEFAULT NULL COMMENT '小写钱包地址',
    market_id VARCHAR(100) DEFAULT NULL COMMENT 'conditionId',
    market_title VARCHAR(500) DEFAULT NULL,
    market_slug VARCHAR(255) DEFAULT NULL,
    asset VARCHAR(120) DEFAULT NULL COMMENT 'token id',
    side VARCHAR(20) DEFAULT NULL COMMENT 'BUY/SELL',
    outcome VARCHAR(100) DEFAULT NULL,
    outcome_index INT DEFAULT NULL,
    price DECIMAL(20, 8) DEFAULT NULL,
    size DECIMAL(20, 8) DEFAULT NULL,
    amount DECIMAL(20, 8) DEFAULT NULL,
    event_time BIGINT NOT NULL COMMENT '事件时间',
    raw_payload_hash VARCHAR(128) NOT NULL,
    payload_summary TEXT DEFAULT NULL,
    usable_for_discovery TINYINT(1) NOT NULL DEFAULT 0,
    usable_for_paper TINYINT(1) NOT NULL DEFAULT 0,
    unusable_reason VARCHAR(255) DEFAULT NULL,
    paper_processing_status VARCHAR(30) NOT NULL DEFAULT 'NEW',
    processing_attempts INT NOT NULL DEFAULT 0,
    paper_processing_started_at BIGINT DEFAULT NULL,
    paper_processed_at BIGINT DEFAULT NULL,
    last_processing_error TEXT DEFAULT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY uk_leader_activity_event_stable_key (stable_event_key),
    UNIQUE KEY uk_leader_activity_event_source_event (source, source_event_id),
    INDEX idx_leader_activity_event_processing (paper_processing_status, event_time),
    INDEX idx_leader_activity_event_wallet_time (normalized_wallet, event_time),
    INDEX idx_leader_activity_event_source_time (source, event_time),
    INDEX idx_leader_activity_event_usable (usable_for_discovery, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Append-only leader activity events';

CREATE TABLE IF NOT EXISTS leader_paper_session (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Paper session ID',
    candidate_id BIGINT NOT NULL COMMENT '候选 ID',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    started_at BIGINT NOT NULL,
    ended_at BIGINT DEFAULT NULL,
    trade_count INT NOT NULL DEFAULT 0,
    filtered_count INT NOT NULL DEFAULT 0,
    open_exposure DECIMAL(20, 8) NOT NULL DEFAULT 0,
    total_realized_pnl DECIMAL(20, 8) NOT NULL DEFAULT 0,
    total_unrealized_pnl DECIMAL(20, 8) NOT NULL DEFAULT 0,
    copyable_pnl DECIMAL(20, 8) NOT NULL DEFAULT 0,
    max_drawdown DECIMAL(20, 8) NOT NULL DEFAULT 0,
    unknown_valuation_exposure DECIMAL(20, 8) NOT NULL DEFAULT 0,
    confirmed_zero_exposure DECIMAL(20, 8) NOT NULL DEFAULT 0,
    filtered_ratio DECIMAL(20, 8) NOT NULL DEFAULT 0,
    last_processed_event_time BIGINT DEFAULT NULL,
    score_snapshot DECIMAL(20, 8) DEFAULT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    INDEX idx_leader_paper_session_candidate_status (candidate_id, status),
    INDEX idx_leader_paper_session_status_started (status, started_at),
    CONSTRAINT fk_leader_paper_session_candidate FOREIGN KEY (candidate_id) REFERENCES leader_research_candidate(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Leader paper trading sessions';

CREATE TABLE IF NOT EXISTS leader_paper_trade (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Paper trade ID',
    session_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    activity_event_id BIGINT DEFAULT NULL,
    leader_trade_id VARCHAR(255) NOT NULL,
    market_id VARCHAR(100) NOT NULL,
    market_title VARCHAR(500) DEFAULT NULL,
    market_slug VARCHAR(255) DEFAULT NULL,
    side VARCHAR(20) NOT NULL,
    outcome VARCHAR(100) DEFAULT NULL,
    outcome_index INT DEFAULT NULL,
    leader_price DECIMAL(20, 8) DEFAULT NULL,
    leader_size DECIMAL(20, 8) DEFAULT NULL,
    simulated_price DECIMAL(20, 8) DEFAULT NULL,
    simulated_size DECIMAL(20, 8) DEFAULT NULL,
    simulated_amount DECIMAL(20, 8) DEFAULT NULL,
    fill_assumption VARCHAR(30) NOT NULL DEFAULT 'LEADER_PRICE',
    quote_confidence VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    quote_source VARCHAR(50) DEFAULT NULL,
    quote_timestamp BIGINT DEFAULT NULL,
    filter_result VARCHAR(30) NOT NULL DEFAULT 'PASSED',
    filter_reason TEXT DEFAULT NULL,
    valuation_status VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    realized_pnl DECIMAL(20, 8) DEFAULT NULL,
    event_time BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    UNIQUE KEY uk_leader_paper_trade_session_trade (session_id, leader_trade_id, side),
    INDEX idx_leader_paper_trade_session_time (session_id, event_time),
    INDEX idx_leader_paper_trade_candidate_time (candidate_id, event_time),
    INDEX idx_leader_paper_trade_activity (activity_event_id),
    CONSTRAINT fk_leader_paper_trade_session FOREIGN KEY (session_id) REFERENCES leader_paper_session(id) ON DELETE CASCADE,
    CONSTRAINT fk_leader_paper_trade_candidate FOREIGN KEY (candidate_id) REFERENCES leader_research_candidate(id) ON DELETE CASCADE,
    CONSTRAINT fk_leader_paper_trade_activity FOREIGN KEY (activity_event_id) REFERENCES leader_activity_event(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Leader paper trades';

CREATE TABLE IF NOT EXISTS leader_paper_position (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Paper position ID',
    session_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    market_id VARCHAR(100) NOT NULL,
    outcome VARCHAR(100) DEFAULT NULL,
    outcome_index INT DEFAULT NULL,
    quantity DECIMAL(20, 8) NOT NULL DEFAULT 0,
    cost DECIMAL(20, 8) NOT NULL DEFAULT 0,
    avg_price DECIMAL(20, 8) NOT NULL DEFAULT 0,
    current_price DECIMAL(20, 8) DEFAULT NULL,
    current_value DECIMAL(20, 8) NOT NULL DEFAULT 0,
    realized_pnl DECIMAL(20, 8) NOT NULL DEFAULT 0,
    unrealized_pnl DECIMAL(20, 8) NOT NULL DEFAULT 0,
    valuation_status VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    quote_confidence VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    quote_source VARCHAR(50) DEFAULT NULL,
    quote_timestamp BIGINT DEFAULT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY uk_leader_paper_position_session_market_outcome (session_id, market_id, outcome_index),
    INDEX idx_leader_paper_position_candidate (candidate_id),
    INDEX idx_leader_paper_position_status (valuation_status),
    CONSTRAINT fk_leader_paper_position_session FOREIGN KEY (session_id) REFERENCES leader_paper_session(id) ON DELETE CASCADE,
    CONSTRAINT fk_leader_paper_position_candidate FOREIGN KEY (candidate_id) REFERENCES leader_research_candidate(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Leader paper positions';

ALTER TABLE copy_trading_leader_pool
    ADD COLUMN research_candidate_id BIGINT DEFAULT NULL COMMENT '关联 research candidate ID',
    ADD COLUMN research_state VARCHAR(30) DEFAULT NULL COMMENT 'Research 状态',
    ADD COLUMN research_badge VARCHAR(50) DEFAULT NULL COMMENT 'Research 推荐 badge',
    ADD COLUMN research_summary TEXT DEFAULT NULL COMMENT 'Research 摘要',
    ADD COLUMN research_score DECIMAL(20, 8) DEFAULT NULL COMMENT 'Research 最新评分',
    ADD COLUMN research_updated_at BIGINT DEFAULT NULL COMMENT 'Research 更新时间',
    ADD INDEX idx_leader_pool_research_candidate (research_candidate_id),
    ADD INDEX idx_leader_pool_research_state (research_state);
